/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ToolCheckInput;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.User;
import model.UserBLL;

/**
 *
 * @author Windows 10 Gamer
 */
public class AddAccountForm extends javax.swing.JFrame {

    private static AddAccountForm object;
    private static AddAccountForm object1;
    private User user;
    private AdminForm parent;
    UserBLL mUserBLL;
    private int userID = 0;

    private AddAccountForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.mUserBLL = new UserBLL();
    }

    /**
     * @return the AddAccountForm
     */
    public static AddAccountForm getObject() {
        if (object == null) {
            object = new AddAccountForm();
        }
        return object;
    }

    private AddAccountForm(AdminForm parent, User user) {
        initComponents();
        setLocationRelativeTo(null);
        this.user = user;
        this.mUserBLL = new UserBLL();
        this.parent = parent;

        txtUserID.setText("" + user.getUserID());
        txtUserName.setText(user.getUserName());
        txtPassword.setText("************");
        txtPhone.setText(user.getUserPhone() + "");
        if (user.getPosition() == 0) {
            cbPosition.setSelectedIndex(0);
        } else if (user.getPosition() == 1) {
            cbPosition.setSelectedIndex(1);
        } else {
            cbPosition.setSelectedIndex(2);
        }

        if (user.getStatus() == 0) {
            cbStatus.setSelectedIndex(0);
        } else {
            cbStatus.setSelectedIndex(1);
        }
        userID = user.getUserID();
    }

    public static AddAccountForm getObject1(AdminForm parent, User user) {
        if (object1 == null) {
            object1 = new AddAccountForm(parent, user);
        } else {
            object1.dispose();
            object1 = new AddAccountForm(parent, user);
        }

        return object1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cbPosition = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        txtUserID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel2.setText("User Name");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Password");

        jLabel5.setText("Position");

        jLabel6.setText("Status");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Receptionist" }));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Blocked" }));

        txtUserID.setEditable(false);

        jLabel7.setText("User ID");

        txtPassword.setEditable(false);
        txtPassword.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCancel)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(btnSave))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(38, 38, 38)
                                    .addComponent(cbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addComponent(txtPassword))))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbStatus, 0, 153, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (userID != 0) {
            if (checkInput()) {
                User userUpdate = new User(
                     userID,
                     txtUserName.getText(),
                     txtPassword.getText(),
                     Integer.parseInt(txtPhone.getText()),
                     cbPosition.getSelectedIndex(),
                     cbStatus.getSelectedIndex()
                );
                if (user.getUserID() == parent.user.getUserID() && user.getPosition() != userUpdate.getPosition()) {
                    int ask = JOptionPane.showConfirmDialog(this, "If you change your position, you will have to login again!", "Warning", JOptionPane.YES_NO_OPTION);
                    if (ask == JOptionPane.YES_OPTION) {
                        int check = mUserBLL.updateUser(userUpdate);
                        if (check == 0) {
                            showNotification("Update Successful");
                            AdminForm.loadData(mUserBLL.getAllUser());
                        } else {
                            showNotification("Update Fail");
                        }
                        this.dispose();
                        parent.dispose();
                        parent.parent.setVisible(true);
                    }
                } else {
                    int check = mUserBLL.updateUser(userUpdate);
                    if (check == 0) {
                        showNotification("Update Successful");
                        AdminForm.loadData(mUserBLL.getAllUser());
                    } else {
                        showNotification("Update Fail");
                    }
                }
            }
        } else if (checkInput()) {
            User newUser = new User(
                 txtUserName.getText(),
                 txtPassword.getText(),
                 Integer.parseInt(txtPhone.getText()),
                 cbPosition.getSelectedIndex(),
                 cbStatus.getSelectedIndex()
            );
            int check = mUserBLL.insertUser(newUser);
            if (check == 0) {
                showNotification("Insert Successful");
                AdminForm.loadData(mUserBLL.getAllUser());
                this.dispose();
            } else {
                showNotification("Insert Fail");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public boolean checkInput() {
        String userName = txtUserName.getText().trim();
        String phoneNumber = txtPhone.getText().trim();

        boolean isUserExist = false;

        try {
            if ((userID == 0 || !user.getUserName().equals(userName)) && mUserBLL.getUserByName(userName).next()) {
                isUserExist = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddAccountForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (userName.isEmpty()) {
            showNotification("User name can not empty !");
            return false;
        } else if (isUserExist) {
            JOptionPane.showMessageDialog(this, "User is already exist", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (phoneNumber.isEmpty()) {
            showNotification("Phone number can not empty !");
            return false;
        } else if (!ToolCheckInput.checkPhoneNumber(phoneNumber)) {
            showNotification("Phone number is incorrect !");
            return false;
        }
        return true;
    }

    public void showNotification(String s) {
        JOptionPane.showMessageDialog(this, s, "Notification", JOptionPane.WARNING_MESSAGE);
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int ask = JOptionPane.showConfirmDialog(this, "Cancel? Your change will not be saved!!", "Warning", JOptionPane.YES_NO_OPTION);
        if (ask == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbPosition;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
