/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.BillBLL;
import model.User;
import model.UserBLL;

/**
 *
 * @author sev_user
 */
public class AdminForm extends javax.swing.JFrame {

    UserBLL mUserBLL;
    BillBLL mBillBLL;
    ResultSet rs;
    User user;
    int selectedUserID = 0; // default = 0: not selected any row
    int selectedRow = -1;
    LoginForm parent;
    private DocumentListener dcListener;
    private static Vector origninalTableModel;

    /**
     * Creates new form AdminForm1
     *
     * @param parent
     */
    public AdminForm(LoginForm parent) {
        initComponents();
        setLocationRelativeTo(null);

        mUserBLL = new UserBLL();
        mBillBLL = new BillBLL();
        this.parent = parent;
        this.user = parent.mUser;
        lbAdminName.setText(parent.mUser.getUserName());

        loadData(mUserBLL.getAllUser());
        addDocumentListener();
        txtUsername.getDocument().addDocumentListener(dcListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPanel = new javax.swing.JScrollPane();
        tblUserList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAddAccount = new javax.swing.JButton();
        btnUpdateAccount = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnChangePass = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jlable = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnResetPass = new javax.swing.JButton();
        lbAdminName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUserList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblUserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User ID", "User Name", "User Phone", "Postion", "Status"
            }
        ));
        tblUserList.setRowHeight(22);
        tblUserList.getTableHeader().setReorderingAllowed(false);
        jScrollPanel.setViewportView(tblUserList);

        jPanel4.add(jScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 1220, 550));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Account List");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 170, 40));

        btnAddAccount.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAddAccount.setText("Add acount");
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 60));

        btnUpdateAccount.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnUpdateAccount.setText("Update account");
        btnUpdateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAccountActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, 60));

        btnDeleteAccount.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });
        jPanel4.add(btnDeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 150, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search Account");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 210, 30));

        txtUsername.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        txtUsername.setText("username");
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        jPanel4.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 180, 210, 40));

        btnChangePass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icon/if_engineering__gear__setting__process__2568275 (1).png"))); // NOI18N
        btnChangePass.setText("setting");
        btnChangePass.setMargin(new java.awt.Insets(2, 5, 2, 25));
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        jPanel4.add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 120, 30));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icon/if_Erase_32464.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setIconTextGap(10);
        btnLogout.setMargin(new java.awt.Insets(2, 5, 2, 25));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 70, 120, 30));

        jlable.setFont(new java.awt.Font("Informal011 BT", 3, 18)); // NOI18N
        jlable.setForeground(new java.awt.Color(0, 255, 51));
        jlable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlable.setText("Welcome");
        jPanel4.add(jlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        jLabel5.setFont(new java.awt.Font("Informal011 BT", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Hotel Management System");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 400, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1460, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icon/if_User_Administrator_3_1218723.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, 120, 110));

        btnResetPass.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnResetPass.setText("Reset Password");
        btnResetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPassActionPerformed(evt);
            }
        });
        jPanel4.add(btnResetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, 60));

        lbAdminName.setFont(new java.awt.Font("Informal011 BT", 3, 18)); // NOI18N
        lbAdminName.setForeground(new java.awt.Color(0, 255, 51));
        lbAdminName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAdminName.setText("Admin");
        jPanel4.add(lbAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/picture/4.jpg"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        ChangePasswordForm.getObject("AdminForm", parent.mUser).setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int ask = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Warning", JOptionPane.YES_NO_OPTION);
        if (ask == JOptionPane.YES_OPTION) {
            parent.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        AddAccountForm.getObject().setVisible(true);
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void btnUpdateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAccountActionPerformed
        User updateUser = new User();
        selectedRow = tblUserList.getSelectedRow();

        if (selectedRow == -1 || tblUserList.getValueAt(selectedRow, 0) == null) {
            JOptionPane.showMessageDialog(this, "select user to update!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String selectedUserName = tblUserList.getValueAt(selectedRow, 1).toString();
            if (selectedUserName.equals("default")) {
                JOptionPane.showMessageDialog(this, "This is default account!! Can not modify!!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                updateUser.setUserID((int) tblUserList.getValueAt(selectedRow, 0));
                updateUser.setUserName((String) tblUserList.getValueAt(selectedRow, 1));
                updateUser.setUserPhone((int) tblUserList.getValueAt(selectedRow, 2));

                String position = tblUserList.getValueAt(selectedRow, 3).toString();
                switch (position) {
                    case "Admin":
                        updateUser.setPosition(0);
                        break;
                    case "Manager":
                        updateUser.setPosition(1);
                        break;
                    default:
                        updateUser.setPosition(2);
                        break;
                }

                String status = tblUserList.getValueAt(selectedRow, 4).toString();
                if (status.equals("Active")) {
                    updateUser.setStatus(0);
                } else {
                    updateUser.setStatus(1);
                }

                AddAccountForm.getObject1(this, updateUser).setVisible(true);
                loadData(mUserBLL.getAllUser());
            }
        }
    }//GEN-LAST:event_btnUpdateAccountActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
        selectedRow = tblUserList.getSelectedRow();

        if (selectedRow == -1 || tblUserList.getValueAt(selectedRow, 0) == null) {
            JOptionPane.showMessageDialog(this, "select user to delete!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String selectedUserName = tblUserList.getValueAt(selectedRow, 1).toString();
            if (selectedUserName.equals("default")) {
                JOptionPane.showMessageDialog(this, "This is default account!! Can not delete!!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                int userID = Integer.parseInt(tblUserList.getValueAt(selectedRow, 0).toString());
                if (userID == parent.mUser.getUserID()) {
                    JOptionPane.showMessageDialog(this, "This user is using system!! Can not delete!!", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {
                    int ask = JOptionPane.showConfirmDialog(this, "Do you really want to delete this user?", "Warning", JOptionPane.YES_NO_OPTION);
                    if (ask == JOptionPane.YES_OPTION) {
                        selectedUserID = (int) tblUserList.getValueAt(selectedRow, 0);
                        if (mUserBLL.deleteUser(selectedUserID) == -1) {
                            int ask1 = JOptionPane.showConfirmDialog(this, "If you delete this user, all bills created by this user will be deleted!!", "Warning", JOptionPane.YES_NO_OPTION);
                            if (ask1 == JOptionPane.YES_OPTION) {
                                mBillBLL.deleteByUserID(selectedUserID);
                                mUserBLL.deleteUser(selectedUserID);
                            }
                        }
                        loadData(mUserBLL.getAllUser());
                    }
                }
            }
        }
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        txtUsername.selectAll();
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void btnResetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPassActionPerformed
        selectedRow = tblUserList.getSelectedRow();

        if (selectedRow == -1 || tblUserList.getValueAt(selectedRow, 0) == null) {
            JOptionPane.showMessageDialog(this, "select user who want to reset password!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String selectedUserName = tblUserList.getValueAt(selectedRow, 1).toString();
            if (selectedUserName.equals("default")) {
                JOptionPane.showMessageDialog(this, "This is default account!! Can not reset password!!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                int ask = JOptionPane.showConfirmDialog(this, "Do you really want to reset password for this user?", "Warning", JOptionPane.YES_NO_OPTION);
                if (ask == JOptionPane.YES_OPTION) {
                    selectedUserID = (int) tblUserList.getValueAt(selectedRow, 0);
                    if (mUserBLL.resetPassword(selectedUserID) == 0) {
                        JOptionPane.showMessageDialog(this, "Password has been reset to default (1)!", "Notify", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnResetPassActionPerformed

    public static void loadData(ResultSet rs) {
        DefaultTableModel tblUserListModel = (DefaultTableModel) tblUserList.getModel();
        tblUserListModel.setRowCount(0);

        try {
            while (rs.next()) {
                String status;
                if (rs.getInt(6) == 0) {
                    status = "Active";
                } else {
                    status = "Blocked";
                }

                String position;
                if (rs.getInt(5) == 0) {
                    position = "Admin";
                } else if (rs.getInt(5) == 1) {
                    position = "Manager";
                } else {
                    position = "Receptionist";
                }
                Object[] data = {
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getInt(4),
                    position,
                    status
                };
                tblUserListModel.addRow(data);
            }

            tblUserList.setModel(tblUserListModel);

        } catch (SQLException ex) {
            Logger.getLogger(RoomManagePanel.class
                 .getName()).log(Level.SEVERE, null, ex);
        }

        origninalTableModel = (Vector) ((DefaultTableModel) (tblUserList.getModel())).getDataVector().clone();
    }

    private void addDocumentListener() {
        dcListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                search();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                search();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                search();
            }

            private void search() {
                searchUser(txtUsername.getText());
            }
        };
    }

    private void searchUser(String userName) {
        DefaultTableModel tblUserModel = (DefaultTableModel) tblUserList.getModel();
        tblUserModel.setRowCount(0);

        for (Object rows : origninalTableModel) {
            Vector rowVector = (Vector) rows;
            if (rowVector.get(1).toString().contains(userName)) {
                tblUserModel.addRow(rowVector);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnResetPass;
    private javax.swing.JButton btnUpdateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlable;
    private javax.swing.JLabel lbAdminName;
    private static javax.swing.JTable tblUserList;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
