/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.ConnectionManager;
import controller.ServerFileController;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Server;
import model.User;
import model.UserBLL;

/**
 *
 * @author Windows 10 Gamer
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    UserBLL mUserBLL;
    User mUser;

    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);

        File f = new File("serverInfo.dat");
        if (!f.exists()) {
            ServerFileController.writeFile(new Server("localhost:1433", "", ""));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSetting = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUserName.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setText("UserName");
        jPanel3.add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 224, -1, -1));
        jPanel3.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, 30));

        lbPassword.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword.setText("Password");
        jPanel3.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, -1));
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 272, 200, 30));

        btnLogin.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnLogin.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icon/if_enter_2199089.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setHideActionText(true);
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnLogin.setMargin(new java.awt.Insets(2, 5, 2, 30));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 130, 40));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hotel Management System");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 440, -1));

        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icon/if_engineering__gear__setting__process__2568275 (1).png"))); // NOI18N
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        jPanel3.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 50, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/picture/1.jpg"))); // NOI18N
        jLabel3.setToolTipText("Config Server");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUserName.getText();
        String password = new String(txtPassword.getPassword());

        if (username == null || username.equals("")) {
            JOptionPane.showMessageDialog(this, "Username can not be null", "Warning", JOptionPane.WARNING_MESSAGE);
            txtUserName.requestFocus();
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Password can not be null", "Warning", JOptionPane.WARNING_MESSAGE);
            txtPassword.requestFocus();
        } else {
            ConnectionManager connectionManager = new ConnectionManager(ServerFileController.readFile());
            if (ConnectionManager.getConnection() == null) {
                JOptionPane.showMessageDialog(this, "Can not connect Database! Please press setting button to config server!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                mUserBLL = new UserBLL();
                mUser = new User();

                //Create default admin account
                try {
                    if (!mUserBLL.getUserByName("default").next()) {
                        System.out.println("1");
                        User defaultUser = new User("default", "123456", 123456789, 0, 0);
                        mUserBLL.insertUser(defaultUser);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                mUser = mUserBLL.getUserLogin(username, password);
                mUserBLL.closeConnetion();
                if (mUser.getUserPass().equals("-1")) {
                    JOptionPane.showMessageDialog(this, "Invalid username or password", "Warning", JOptionPane.WARNING_MESSAGE);
                    txtUserName.requestFocus();
                } else if (mUser.getStatus() == 1) {
                    JOptionPane.showMessageDialog(this, "Your account is blocked! Please contact admin for more detail!", "Warning", JOptionPane.WARNING_MESSAGE);
                } else if (mUser.getUserPass().equals("1")) {
                    int ask = JOptionPane.showConfirmDialog(this, "Your password is currently set as default by admin! Do you want to change?", "Warning", JOptionPane.YES_NO_OPTION);
                    if (ask == JOptionPane.YES_OPTION) {
                        ChangePasswordForm.getObject("Login", mUser).setVisible(true);
                    } else {
                        switch (mUser.getPosition()) {
                            case 0:
                                new AdminForm(this).setVisible(true);
                                this.dispose();
                                break;
                            case 1:
                                new ManagerForm(this).setVisible(true);
                                this.dispose();
                                break;
                            default:
                                new ReceptionistForm(this).setVisible(true);
                                this.dispose();
                                break;
                        }
                    }
                } else {
                    switch (mUser.getPosition()) {
                        case 0:
                            new AdminForm(this).setVisible(true);
                            this.dispose();
                            break;
                        case 1:
                            new ManagerForm(this).setVisible(true);
                            this.dispose();
                            break;
                        default:
                            new ReceptionistForm(this).setVisible(true);
                            this.dispose();
                            break;
                    }
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        ServerConfigDialog dialog = new ServerConfigDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
